- name: Install the package bash-completion
  ansible.builtin.apt:
    name: bash-completion

- name: Enable kubectl bash completion
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'source <(kubectl completion bash)'
    state: present
